name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm install
  
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: |
        npm run raw --reporter=line,allure-playwright
    - name: Install Allure Commandline
      run: npm install -g allure-commandline

    - name: Generate Allure Report
      run: |
        export ALLURE_RESULTS_DIR=allure-results
        allure generate $ALLURE_RESULTS_DIR --clean -o allure-report


    - name: Upload Allure Report
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: allure-report
#test
